// Copyright by Barry G Becker, 2013 - 2026. Licensed under MIT License: http://www.opensource.org/licenses/MIT
// @author Barry G Becker

plugins {
    id 'com.barrybecker4.bb4.scala-library' version '2.0-SNAPSHOT'
    id 'com.barrybecker4.bb4.publish' version '2.0-SNAPSHOT'
    id 'com.barrybecker4.bb4.application' version '2.0-SNAPSHOT'
    id 'com.github.maiflai.scalatest' version '0.33'
}

description = 'A library project containing bb4 common code'
group = 'com.barrybecker4'
version = '2.0-SNAPSHOT'

bb4 {
    archivesBaseName.set('bb4-common')
    mainClass.set('com.barrybecker4.common.app.AppContext')
}
