// Copyright by Barry G Becker, 2013 - 2026. Licensed under MIT License: http://www.opensource.org/licenses/MIT

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = 'https://central.sonatype.com/repository/maven-snapshots/' }
    }
}

rootProject.name = 'bb4-common'
